### ISSUE TITLE
Script Fetching incorrect FromId ??

### ISSUE THREAD

**Issue by milyasyousuf** [ihalloum/FacebookScraper#1]
Assalam o Alekum,
I have cloned your script for my university project. Your script is very awesome. But it gives me an error. When I fetch data it given me incorrect FormId. Can you please guide how can I correct it??
![screenshot from 2016-05-05 22-43-08](https://cloud.githubusercontent.com/assets/12115122/15051583/d4cca72c-1312-11e6-837d-11a5ab54ac45.png)
![screenshot from 2016-05-05 22-43-30](https://cloud.githubusercontent.com/assets/12115122/15051584/d4fa6b30-1312-11e6-8849-2d3024e4f383.png)
Waiting for you reply,

**Comment by ihalloum** [comment]
Dear ,
I don't know why graph online tool show this error , i try to user same user id in online graph tool and directly with HTTP request and i have this result .
the script store correct value and i will search about this problem and tell you.

thanks.

![capture1](https://cloud.githubusercontent.com/assets/10779546/15083791/ebc6a656-13d7-11e6-9b05-2adcb8a1b6bc.JPG)
![capture2](https://cloud.githubusercontent.com/assets/10779546/15083790/ebc68fc2-13d7-11e6-9cf3-152bc092d30f.JPG)
![capture3](https://cloud.githubusercontent.com/assets/10779546/15083792/ebce2be2-13d7-11e6-84ba-495a1f2c313a.JPG)

**Comment by milyasyousuf** [comment]
Thanks for your reply. I will be waiting for your answer.
